### ISSUE TITLE
Strange output on prompt Git repo folder

### ISSUE THREAD

**Issue by greduan** [yonchu/zsh-vcs-prompt#6]
Steps to reproduce:

```
$ cd ~/.zsh/zsh-vcs-prompt
# watch prompt
```

Basically I get a very strange output, observe:
![Screen Shot 2012-12-13 at 10 32 25 AM](https://f.cloud.github.com/assets/2314074/11112/b2623d2e-4542-11e2-9688-0b62209dcc45.png)

So as you can see, it _only_ happens when you're inside the folder with the prompt's file's. It doesn't happen on any other folder (as shown).

\- Eduan

**Comment by yonchu** [comment]
Sorry!
Modified formats specification.

Since then, I've thought the specification of formats over again.
And I've found out that the variables to define colors is not necessary. So, obsoleted it.
In addition, changed escape sequences that start with "%" to "#".

Sorry, but please change your settings.
For more details, please refer to README.

Probably I think you have only to delete the variables about formats (ZSH_VCS_PROMPT_*_FORMATS).

**Comment by greduan** [comment]
Ah I see, updating it fixed it, thanks!
